// <auto-generated />
using System;
using GreenDelight.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenDelight.Persistence.Migrations
{
    [DbContext(typeof(GreenDelightDbContext))]
    [Migration("20250111111517_mig_add_example_project_try")]
    partial class mig_add_example_project_try
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GreenDelight.Domain.Concrete.About", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Abouts");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.Adress", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("No")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("UserId");

                    b.ToTable("Adresses");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.Comment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CommentDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.Contact", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.ErrorLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ErrorCode")
                        .HasColumnType("int");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserIpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.OrderItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductID");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.Bolge", b =>
                {
                    b.Property<short>("BolgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("BolgeId"));

                    b.Property<string>("BolgeAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BolgeKisaAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BolgeId");

                    b.ToTable("Bolge");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.GorevTur", b =>
                {
                    b.Property<short>("GorevTurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("GorevTurId"));

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GorevTurId");

                    b.ToTable("GorevTur");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.Gorevlendirme", b =>
                {
                    b.Property<long>("GorevlendirmeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GorevlendirmeId"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BelgenetSayi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BelgenetTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("BirimAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirimTur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("GorevTurId")
                        .HasColumnType("smallint");

                    b.Property<int>("GorevlendirilecekPersonelNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("GorevlendirmeBaslangic")
                        .HasColumnType("datetime2");

                    b.Property<string>("GorevlendirmeBirim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GorevlendirmeBitis")
                        .HasColumnType("datetime2");

                    b.Property<short>("GorevlendirmeTurId")
                        .HasColumnType("smallint");

                    b.Property<int?>("PersonelId")
                        .HasColumnType("int");

                    b.HasKey("GorevlendirmeId");

                    b.HasIndex("GorevTurId");

                    b.HasIndex("GorevlendirmeTurId");

                    b.HasIndex("PersonelId");

                    b.ToTable("Gorevlendirme");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.GorevlendirmeTur", b =>
                {
                    b.Property<short>("GorevlendirmeTurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("GorevlendirmeTurId"));

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GorevlendirmeTurId");

                    b.ToTable("GorevlendirmeTur");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.GunlukVardiyaIstasyonBirim", b =>
                {
                    b.Property<long>("GunlukVardiyaIstasyonBirimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GunlukVardiyaIstasyonBirimId"));

                    b.Property<int>("IstasyonBirimId")
                        .HasColumnType("int");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("VardiyaId")
                        .HasColumnType("int");

                    b.HasKey("GunlukVardiyaIstasyonBirimId");

                    b.HasIndex("IstasyonBirimId");

                    b.HasIndex("PersonelId");

                    b.HasIndex("VardiyaId");

                    b.ToTable("GunlukVardiyaIstasyonBirim");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.GunlukVardiyaMasa", b =>
                {
                    b.Property<long>("GunlukVardiyaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GunlukVardiyaId"));

                    b.Property<short>("MasaId")
                        .HasColumnType("smallint");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("VardiyaId")
                        .HasColumnType("int");

                    b.HasKey("GunlukVardiyaId");

                    b.HasIndex("MasaId");

                    b.HasIndex("PersonelId");

                    b.HasIndex("VardiyaId");

                    b.ToTable("GunlukVardiyaMasa");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.Istasyon", b =>
                {
                    b.Property<int>("IstasyonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IstasyonId"));

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("IstasyonAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IstasyonKod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IstasyonId");

                    b.ToTable("Istasyon");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.IstasyonBirim", b =>
                {
                    b.Property<int>("IstasyonBirimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IstasyonBirimId"));

                    b.Property<short>("IstasyonBirimTurId")
                        .HasColumnType("smallint");

                    b.Property<int>("IstasyonId")
                        .HasColumnType("int");

                    b.HasKey("IstasyonBirimId");

                    b.HasIndex("IstasyonBirimTurId");

                    b.HasIndex("IstasyonId");

                    b.ToTable("IstasyonBirim");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.IstasyonBirimTur", b =>
                {
                    b.Property<short>("IstasyonBirimTurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("IstasyonBirimTurId"));

                    b.Property<string>("IstasyonBirimTurTanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IstasyonBirimTurId");

                    b.ToTable("IstasyonBirimTur");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.IstasyonDurum", b =>
                {
                    b.Property<int>("IstasyonDurumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IstasyonDurumId"));

                    b.Property<DateTime?>("BaslangicZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BitisZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GecerlilikBaslangic")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GecerlilikBitis")
                        .HasColumnType("datetime2");

                    b.Property<int>("IstasyonDurumTurId")
                        .HasColumnType("int");

                    b.Property<int>("IstasyonId")
                        .HasColumnType("int");

                    b.HasKey("IstasyonDurumId");

                    b.HasIndex("IstasyonDurumTurId");

                    b.HasIndex("IstasyonId");

                    b.ToTable("IstasyonDurum");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.IstasyonDurumTur", b =>
                {
                    b.Property<int>("IstasyonDurumTurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IstasyonDurumTurId"));

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IstasyonDurumTurId");

                    b.ToTable("IstasyonDurumTur");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.IzinTur", b =>
                {
                    b.Property<short>("IzinTurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("IzinTurId"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IzinTurId");

                    b.ToTable("IzinTur");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.Masa", b =>
                {
                    b.Property<short>("MasaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("MasaId"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsClone")
                        .HasColumnType("bit");

                    b.Property<short?>("ParentId")
                        .HasColumnType("smallint");

                    b.Property<string>("Renk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("TrafikYonetimMerkeziId")
                        .HasColumnType("smallint");

                    b.HasKey("MasaId");

                    b.HasIndex("ParentId");

                    b.HasIndex("TrafikYonetimMerkeziId");

                    b.ToTable("Masa");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.Mesai", b =>
                {
                    b.Property<long>("MesaiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MesaiId"));

                    b.Property<DateTime?>("MesaiBaslangic")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MesaiBitis")
                        .HasColumnType("datetime2");

                    b.Property<short?>("MesaiTurId")
                        .HasColumnType("smallint");

                    b.Property<int?>("PersonelNo")
                        .HasColumnType("int");

                    b.Property<int?>("PersonelNoNavigationPersonelId")
                        .HasColumnType("int");

                    b.HasKey("MesaiId");

                    b.HasIndex("MesaiTurId");

                    b.HasIndex("PersonelNoNavigationPersonelId");

                    b.ToTable("Mesai");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.MesaiTur", b =>
                {
                    b.Property<short>("MesaiTurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("MesaiTurId"));

                    b.Property<string>("Birim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MesaiTurTanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MesaiTurId");

                    b.ToTable("MesaiTur");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.OrgBirim", b =>
                {
                    b.Property<long>("OrgBirimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrgBirimId"));

                    b.Property<string>("OrgBirimKod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgBirimTanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UstOrgBirimKod")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrgBirimId");

                    b.ToTable("OrgBirim");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.Personel", b =>
                {
                    b.Property<int>("PersonelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonelId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgBirimKod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("OrgBirimKodNavigationOrgBirimId")
                        .HasColumnType("bigint");

                    b.Property<int>("PersonelNo")
                        .HasColumnType("int");

                    b.Property<string>("SicilNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TcKimlikNo")
                        .HasColumnType("bigint");

                    b.HasKey("PersonelId");

                    b.HasIndex("OrgBirimKodNavigationOrgBirimId");

                    b.ToTable("Personel");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.PersonelIzin", b =>
                {
                    b.Property<int>("PersonelIzinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonelIzinId"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IzinBaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IzinBitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<short>("IzinTurId")
                        .HasColumnType("smallint");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.HasKey("PersonelIzinId");

                    b.HasIndex("IzinTurId");

                    b.HasIndex("PersonelId");

                    b.ToTable("PersonelIzin");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.TrafikYonetimMerkezi", b =>
                {
                    b.Property<short>("TrafikYonetimMerkeziId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("TrafikYonetimMerkeziId"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("BirimKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("BolgeId")
                        .HasColumnType("smallint");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrafikYonetimMerkeziId");

                    b.HasIndex("BolgeId");

                    b.ToTable("TrafikYonetimMerkezi");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.Vardiya", b =>
                {
                    b.Property<int>("VardiyaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VardiyaId"));

                    b.Property<TimeOnly>("BaslangicSaat")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("BitisSaat")
                        .HasColumnType("time");

                    b.Property<short?>("SiraNo")
                        .HasColumnType("smallint");

                    b.Property<int>("VardiyaSablonId")
                        .HasColumnType("int");

                    b.HasKey("VardiyaId");

                    b.HasIndex("VardiyaSablonId");

                    b.ToTable("Vardiya");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.VardiyaSablonYer", b =>
                {
                    b.Property<int>("VardiyaSablonYerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VardiyaSablonYerId"));

                    b.Property<DateTime?>("GecerlilikBaslangic")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GecerlilikBitis")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IstasyonBirimId")
                        .HasColumnType("int");

                    b.Property<short?>("MasaId")
                        .HasColumnType("smallint");

                    b.Property<short>("MaxVardiya")
                        .HasColumnType("smallint");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VardiyaSablonYerId");

                    b.HasIndex("IstasyonBirimId");

                    b.HasIndex("MasaId");

                    b.ToTable("VardiyaSablonYer");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.Adress", b =>
                {
                    b.HasOne("GreenDelight.Domain.Concrete.User", "User")
                        .WithMany("Adresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.Comment", b =>
                {
                    b.HasOne("GreenDelight.Domain.Concrete.Product", "Product")
                        .WithMany("Comments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenDelight.Domain.Concrete.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.Order", b =>
                {
                    b.HasOne("GreenDelight.Domain.Concrete.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.OrderItem", b =>
                {
                    b.HasOne("GreenDelight.Domain.Concrete.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenDelight.Domain.Concrete.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.Product", b =>
                {
                    b.HasOne("GreenDelight.Domain.Concrete.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.Gorevlendirme", b =>
                {
                    b.HasOne("GreenDelight.Domain.Concrete.TryEntities.GorevTur", "GorevTur")
                        .WithMany("Gorevlendirme")
                        .HasForeignKey("GorevTurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenDelight.Domain.Concrete.TryEntities.GorevlendirmeTur", "GorevlendirmeTur")
                        .WithMany("Gorevlendirme")
                        .HasForeignKey("GorevlendirmeTurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenDelight.Domain.Concrete.TryEntities.Personel", "Personel")
                        .WithMany("Gorevlendirme")
                        .HasForeignKey("PersonelId");

                    b.Navigation("GorevTur");

                    b.Navigation("GorevlendirmeTur");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.GunlukVardiyaIstasyonBirim", b =>
                {
                    b.HasOne("GreenDelight.Domain.Concrete.TryEntities.IstasyonBirim", "IstasyonBirim")
                        .WithMany("GunlukVardiyaIstasyonBirim")
                        .HasForeignKey("IstasyonBirimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenDelight.Domain.Concrete.TryEntities.Personel", "Personel")
                        .WithMany("GunlukVardiyaIstasyonBirim")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenDelight.Domain.Concrete.TryEntities.Vardiya", "Vardiya")
                        .WithMany("GunlukVardiyaIstasyonBirim")
                        .HasForeignKey("VardiyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IstasyonBirim");

                    b.Navigation("Personel");

                    b.Navigation("Vardiya");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.GunlukVardiyaMasa", b =>
                {
                    b.HasOne("GreenDelight.Domain.Concrete.TryEntities.Masa", "Masa")
                        .WithMany("GunlukVardiyaMasa")
                        .HasForeignKey("MasaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenDelight.Domain.Concrete.TryEntities.Personel", "Personel")
                        .WithMany("GunlukVardiyaMasa")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenDelight.Domain.Concrete.TryEntities.Vardiya", "Vardiya")
                        .WithMany("GunlukVardiyaMasa")
                        .HasForeignKey("VardiyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Masa");

                    b.Navigation("Personel");

                    b.Navigation("Vardiya");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.IstasyonBirim", b =>
                {
                    b.HasOne("GreenDelight.Domain.Concrete.TryEntities.IstasyonBirimTur", "IstasyonBirimTur")
                        .WithMany("IstasyonBirim")
                        .HasForeignKey("IstasyonBirimTurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenDelight.Domain.Concrete.TryEntities.Istasyon", "Istasyon")
                        .WithMany("IstasyonBirim")
                        .HasForeignKey("IstasyonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Istasyon");

                    b.Navigation("IstasyonBirimTur");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.IstasyonDurum", b =>
                {
                    b.HasOne("GreenDelight.Domain.Concrete.TryEntities.IstasyonDurumTur", "IstasyonDurumTur")
                        .WithMany("IstasyonDurum")
                        .HasForeignKey("IstasyonDurumTurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenDelight.Domain.Concrete.TryEntities.Istasyon", "Istasyon")
                        .WithMany("IstasyonDurum")
                        .HasForeignKey("IstasyonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Istasyon");

                    b.Navigation("IstasyonDurumTur");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.Masa", b =>
                {
                    b.HasOne("GreenDelight.Domain.Concrete.TryEntities.Masa", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId");

                    b.HasOne("GreenDelight.Domain.Concrete.TryEntities.TrafikYonetimMerkezi", "TrafikYonetimMerkezi")
                        .WithMany("Masa")
                        .HasForeignKey("TrafikYonetimMerkeziId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("TrafikYonetimMerkezi");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.Mesai", b =>
                {
                    b.HasOne("GreenDelight.Domain.Concrete.TryEntities.MesaiTur", "MesaiTur")
                        .WithMany("Mesai")
                        .HasForeignKey("MesaiTurId");

                    b.HasOne("GreenDelight.Domain.Concrete.TryEntities.Personel", "PersonelNoNavigation")
                        .WithMany("Mesai")
                        .HasForeignKey("PersonelNoNavigationPersonelId");

                    b.Navigation("MesaiTur");

                    b.Navigation("PersonelNoNavigation");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.Personel", b =>
                {
                    b.HasOne("GreenDelight.Domain.Concrete.TryEntities.OrgBirim", "OrgBirimKodNavigation")
                        .WithMany("Personel")
                        .HasForeignKey("OrgBirimKodNavigationOrgBirimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrgBirimKodNavigation");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.PersonelIzin", b =>
                {
                    b.HasOne("GreenDelight.Domain.Concrete.TryEntities.IzinTur", "IzinTur")
                        .WithMany("PersonelIzin")
                        .HasForeignKey("IzinTurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenDelight.Domain.Concrete.TryEntities.Personel", "Personel")
                        .WithMany("PersonelIzin")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IzinTur");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.TrafikYonetimMerkezi", b =>
                {
                    b.HasOne("GreenDelight.Domain.Concrete.TryEntities.Bolge", "Bolge")
                        .WithMany("TrafikYonetimMerkezi")
                        .HasForeignKey("BolgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bolge");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.Vardiya", b =>
                {
                    b.HasOne("GreenDelight.Domain.Concrete.TryEntities.VardiyaSablonYer", "VardiyaSablon")
                        .WithMany("Vardiya")
                        .HasForeignKey("VardiyaSablonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VardiyaSablon");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.VardiyaSablonYer", b =>
                {
                    b.HasOne("GreenDelight.Domain.Concrete.TryEntities.IstasyonBirim", "IstasyonBirim")
                        .WithMany("VardiyaSablonYer")
                        .HasForeignKey("IstasyonBirimId");

                    b.HasOne("GreenDelight.Domain.Concrete.TryEntities.Masa", "Masa")
                        .WithMany("VardiyaSablonYer")
                        .HasForeignKey("MasaId");

                    b.Navigation("IstasyonBirim");

                    b.Navigation("Masa");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("GreenDelight.Domain.Concrete.UserRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("GreenDelight.Domain.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("GreenDelight.Domain.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("GreenDelight.Domain.Concrete.UserRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenDelight.Domain.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("GreenDelight.Domain.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.Product", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.Bolge", b =>
                {
                    b.Navigation("TrafikYonetimMerkezi");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.GorevTur", b =>
                {
                    b.Navigation("Gorevlendirme");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.GorevlendirmeTur", b =>
                {
                    b.Navigation("Gorevlendirme");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.Istasyon", b =>
                {
                    b.Navigation("IstasyonBirim");

                    b.Navigation("IstasyonDurum");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.IstasyonBirim", b =>
                {
                    b.Navigation("GunlukVardiyaIstasyonBirim");

                    b.Navigation("VardiyaSablonYer");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.IstasyonBirimTur", b =>
                {
                    b.Navigation("IstasyonBirim");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.IstasyonDurumTur", b =>
                {
                    b.Navigation("IstasyonDurum");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.IzinTur", b =>
                {
                    b.Navigation("PersonelIzin");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.Masa", b =>
                {
                    b.Navigation("GunlukVardiyaMasa");

                    b.Navigation("InverseParent");

                    b.Navigation("VardiyaSablonYer");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.MesaiTur", b =>
                {
                    b.Navigation("Mesai");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.OrgBirim", b =>
                {
                    b.Navigation("Personel");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.Personel", b =>
                {
                    b.Navigation("Gorevlendirme");

                    b.Navigation("GunlukVardiyaIstasyonBirim");

                    b.Navigation("GunlukVardiyaMasa");

                    b.Navigation("Mesai");

                    b.Navigation("PersonelIzin");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.TrafikYonetimMerkezi", b =>
                {
                    b.Navigation("Masa");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.Vardiya", b =>
                {
                    b.Navigation("GunlukVardiyaIstasyonBirim");

                    b.Navigation("GunlukVardiyaMasa");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.TryEntities.VardiyaSablonYer", b =>
                {
                    b.Navigation("Vardiya");
                });

            modelBuilder.Entity("GreenDelight.Domain.Concrete.User", b =>
                {
                    b.Navigation("Adresses");

                    b.Navigation("Comments");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
